.TH PRNALIGN 1 "Release 3.0" "Scoring Pkg"
.SH NAME
prnalign - Print several system alignment files to stdout
.SH SYNOPSIS
prnalign -d alignment-file1 alignment-file2 . . . . 
.SH DESCRIPTION
pralign opens the alignment files and prints all the matching sentences
of each systems to stdout.

If '-d' is specified, only the sentences with differing alignments are
printed out.
.SH SEE ALSO
align(1)
.SH BUGS
If you see `em, smash `em!
