.TH TAL_INTR 1 "Release 3.3" "Scoring Pkg"
.SH NAME
tal_intr - Test the C-Language interface to the alignment code
.SH SYNOPSIS
tal_intr table_of_codesets
.SH DESCRIPTION
tal_intr uses the C-Language interface to the NIST string alignment
programs and demostrates how the interface is used.  The program
makes use of the following functions define in 'doc/score.rdm':
align_init(), align_strings(), align_close(), and print_SCORE_T().

.SH SEE ALSO

.SH BUGS
If you see `em, smash `em!
