.TH CHGNAME 1 "Release 3.0" "Scoring Pkg"	
.SH NAME
chgname - Change the system name of an system alignment file
.SH SYNOPSIS
chgname alignment-file system-name
.SH DESCRIPTION
.PP
chgname opens the file "alignment-file", rewrites the system name to
"system-name" then writes out the new version.
.SH SEE ALSO
align(1)
.SH BUGS
If you see `em, smash `em!
