.TH PREPHYPS 1 "Release 3.0" "Scoring Pkg"
.SH NAME
prephyps - given a file of hypothesis sentences, sort and capitalize
all of the sentences
.SH SYNOPSIS
prepare_hyps hyp-file-name <hyp-file-output>
.SH DESCRIPTION
Sort and capitalize hypothesis sentences in the file "hyp-file-name"
into the file "hyp-file-output".  If "hyp-file-output" is omitted from
the command line, the sorted sentences are written back into
"hyp-file-name".
.SH SEE ALSO
align(1)
.SH BUGS
If you see `em, smash `em!
