.TH PRNTNAME 1 "Release 3.0" "Scoring Pkg"
.SH NAME
prntname - Print the system name and description of a system alignment file
.SH SYNOPSIS
prntname alignment-file
.SH DESCRIPTION
pralign opens the file "alignment-file" and prints the system name and
description.
.SH SEE ALSO
align(1)
.SH BUGS
If you see `em, smash `em!
