.TH homo 5 "Release 3.3" "Scoring Pkg"
.SH NAME
homo - Definition of words pronounced identically
.SH DESCRIPTION
A file of Homophones is a list of word pairs whose pronounications are identical.  Each pair is on a signle line, and each word is separated by
whitespace.  Below is an except from the RM homophone file found in
'lib/rm/homophone.txt':

.RS
;;  Comment lines
.RE
.RS
;;  Comment lines
.RE
.RS
WHO+S          WHOSE
.RE
.RS
WEEKS          WEEK+S
.RE
.RS
TEXAS          TEXAS+S
.RE
.RS
TWO            TO
.RE
.RS
DUE            DO
.RE
.RS
THERE          THEIR
.RE
.RS
FOUR           FOR
.RE
.RS
CARRIERS       CARRIER+S
.RE
.RS
CRUISERS       CRUISER+S
.RE
.RS
CRUISER+S      CRUISERS+S
.RE
.RS
CRUISERS+S     CRUISERS
.RE

.SH SEE ALSO


